version: '3.5'
services:
  workshop-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - service-network


  workshop-kafka:
    image: 'wurstmeister/kafka:2.12-2.3.1'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: workshop-kafka
      KAFKA_ZOOKEEPER_CONNECT: workshop-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - workshop-zookeeper
    networks:
      - service-network

networks:
  service-network:
    name: workshop-network